<?php
/*
 * @file
 * Main module file for Student.
 */

/*
 * Implements hook_entity_info().
 */
function student_entity_info() {

  $entities = array();

  $entities['student'] = array(
    'label' => t('Student'),
    'access callback' => 'student_access',
    'uri callback' => 'student_uri',
    'controller class' => 'StudentController',
    'base table' => 'student',
    'label callback' => 'student_label',
    'entity keys' => array(
      'id' => 'student_id',
      'bundle' => 'type',
    ),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'bundles' => array(),
    'static cache' => TRUE,
    'fieldable' => TRUE,
    'module' => 'student',
    'view modes' => array(
      'full' => array(
        'label' => t('Full content'),
        'custom settings' => TRUE,
      ),
      'teaser' => array(
        'label' => t('Teaser'),
        'custom settings' => TRUE,
      ),
    ),
    'redirect' => FALSE, // Redirect module
  );

  foreach (student_types() as $machine_name => $type) {
    $entities['student']['bundles'][$machine_name] = array(
      'label' => drupal_ucfirst($type['name']),
      'admin' => array(
        'path' => 'admin/config/students/' . $machine_name,
        'real path' => 'admin/config/students/' . $machine_name,
        'bundle argument' => 3,
        'access arguments' => array('administer students'),
      ),
      'redirect' => FALSE, // Redirect module
    );
  }

  return $entities;

}

/*
 * Implements hook_entity_property_info().
 *
 * See http://drupalcontrib.org/api/drupal/contributions--entity--entity.api.php/function/hook_entity_property_info/7
 *
 * Not in use yet.
 */
function student_entity_property_info() {
  $info = array();
  $properties = &$info['student']['properties'];
  $properties['student_id'] = array(
    'label' => t('Student ID'),
    'type' => 'integer',
    'description' => t('The unique ID of the student entity.'),
    'schema field' => 'student_id',
  );
  $properties['type'] = array(
    'label' => t('Type'),
    'type' => 'token',
    'description' => t('The type of student (machine-readable name).'),
    'required' => TRUE,
    'schema field' => 'type',
  );
  $properties['uid'] = array(
    'label' => t('User ID'),
    'type' => 'integer',
    'description' => t('The Drupal user ID associated with the student.'),
    'validation callback' => 'student_validate_uid',
    'schema field' => 'uid',
  );
  $properties['uuid'] = array(
    'label' => t('UUID'),
    'type' => 'text',
    'description' => t('The universally unique identifier of the student.'),
    'schema field' => 'uuid',
  );
  $properties['created'] = array(
    'label' => t('Created date'),
    'type' => 'date',
    'description' => t('The date and time when the student entity was created.'),
    'schema field' => 'created',
  );
  $properties['changed'] = array(
    'label' => t('Changed date'),
    'type' => 'date',
    'description' => t('The date and time when the student entity was last modified.'),
    'schema field' => 'changed',
  );
  return $properties;
}

/*
 * Validation callback for the student property 'uid'.
 *
 * @see student_entity_property_info()
 */
function student_validate_uid($uid) {
  if (is_numeric($uid) && $account = user_load($uid)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_menu().
 */
function student_menu() {

  $items = array();

  $items['admin/config/students'] = array(
    'title' => 'Students',
    'description' => 'Administer students.',
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer students'),
  );

  $items['admin/config/students/list'] = array(
    'title' => 'Student list',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('student_list_form'),
    'access arguments' => array('administer students'),
    'file' => 'student.admin.inc',
    'description' => 'View, edit, and add new students.',
    'weight' => -10,
  );

  foreach (student_types() as $machine_name => $type) {
    $items['admin/config/students/list/add/' . $machine_name] = array(
      'title' => 'Add new ' . $type['name'],
      'title callback' => 'check_plain',
      'page callback' => 'student_page_add',
      'page arguments' => array(5),
      'access arguments' => array('administer students'),
      'file' => 'student.admin.inc',
      'description' => empty($type['description'])? '' : $type['description'],
      'type' => MENU_LOCAL_ACTION,
    );
    $items['admin/config/students/' . $machine_name] = array(
      'title' => drupal_ucfirst($type['name']) . ' settings',
      'title callback' => 'check_plain',
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('administer students'),
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
      'description' => empty($type['description'])? '' : $type['description'],
    );
  }

  $items['student/%student'] = array(
    'title callback' => 'student_page_title',
    'title arguments' => array(1),
    'page callback' => 'student_page_view',
    'page arguments' => array(1),
    'access callback' => 'student_access',
    'access arguments' => array('view', 2),
    'file' => 'student.pages.inc',
  );

  $items['student/%student/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );

  $items['student/%student/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'student_page_edit',
    'file' => 'student.admin.inc',
    'page arguments' => array(1),
    'access callback' => 'student_access',
    'access arguments' => array('update', 1),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  $items['student/%student/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('student_form_delete_confirm', 1),
    'access callback' => 'student_access',
    'access arguments' => array('delete', 1),
    'file' => 'student.admin.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
  );

  return $items;

}

/**
 * Return information about student types in a structured array, keyed by
 * each type's machine name. Each element is also a structured array defining at
 * least 'name'.
 *
 * This uses hook_student_type_info() to allow other modules to define types.
 *
 * @return array
 */
function student_types() {
  $types = &drupal_static(__FUNCTION__);
  if (empty($types)) {
    $types = array();
    $types += module_invoke_all('student_type_info');
  }
  return $types;
}

/**
 * Load student type information by its machine name.
 *
 * @param string $machine_name
 *   The machine name of the type.
 * @return mixed
 *   A stdClass election type object, or FALSE on failure.
 */
function student_type_get_info($machine_name) {
  $type = array(
    'name' => t('Unknown type'),
  );
  $types = student_types();
  if (isset($types[$machine_name])) {
    $type = $types[$machine_name];
  }
  return $type;
}

/**
 * Implements hook_permission().
 *
 * @return array
 */
function student_permission() {
  $permissions = array(
    'administer students' => array(
      'title' => t('Administer students'),
      'description' => t('Alter the fields and display settings for student types.'),
    ),
    'create student' => array(
      'title' => t('Create any students'),
    ),
    'delete student' => array(
      'title' => t('Delete any students'),
      'description' => t('This permission is dangerous: deleting an student automatically deletes ALL associated data.'),
      'restrict access' => TRUE,
    ),
    'edit student' => array(
      'title' => t('Edit any student'),
    ),
    'view student' => array(
      'title' => t('View any student'),
    ),
  );
  return $permissions;
}

/**
 * Implements entity_uri(). URI callback for a single student. See:
 * http://api.drupal.org/api/drupal/includes--common.inc/function/entity_uri/7.
 *
 * @param stdClass $entity
 *
 * @return array
 */
function student_uri(stdClass $student) {
  $path = 'student/' . $student->student_id;
  return array(
    'path' => $path,
  );
}

/**
 * Determines whether the given user has access to a Student.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $student
 *   Optionally a student o check access for. If nothing is given, access for
 *   all students is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function student_access($op, $student = NULL, $account = NULL) {
  switch ($op) {
    case 'view':
      return (bool) user_access('view student', $account);
      break;
    case 'create':
      return (bool) user_access('create student', $account);
      break;
    case 'update':
    case 'edit':
      return (bool) user_access('edit student', $account);
      break;
    case 'delete':
      return (bool) user_access('delete student', $account);
      break;
  }
  return FALSE;
}

/**
 * Load an individual student.
 *
 * @param mixed $student_id
 *   A single student ID.
 *
 * @return stdClass
 *   A stdClass student object.
 */
function student_load($student_id = NULL) {
  $result = entity_load('student', (array) $student_id);
  if (!is_array($result) || !count($result)) {
    return FALSE;
  }
  return reset($result);
}

/**
 * Load multiple students.
 *
 * @param mixed $student_id
 *   An array of student IDs.
 *
 * @return stdClass
 *   A stdClass student object.
 */
function student_load_multiple(array $student_ids = array()) {
  return entity_load('student', $student_ids);
}

/**
 * Wrapper function to allow deleting multiple students.
 *
 * @param array $student_ids
 *   Array of student IDs.
 * @return bool
 */
function student_delete_multiple(array $student_ids) {
  return entity_get_controller('student')->delete($student_ids);
}

/**
 * Wrapper function to allow deleting an individual student.
 *
 * @see student_delete_multiple()
 *
 * @param mixed $student_id
 *   Single student ID.
 * @return bool
 */
function student_delete($student_id) {
  return student_delete_multiple(array($student_id));
}

/**
 * Wrapper function to allow saving a student.
 *
 * @param stdClass $student
 *   student object.
 * @return bool
 */
function student_save(stdClass $student) {
  return entity_get_controller('student')->save($student);
}

/*
 * Student entity label callback.
 *
 * Note that for Drupal 8 the parameter order for label callbacks will be
 * reversed.
 *
 * @param stdClass $entity
 */
function student_label(stdClass $entity, $entity_type) {

  if ($entity_type != 'student') {
    return FALSE;
  }

  if (!empty($entity->uuid)) {
    return t('Student (UUID @uuid)', array('@uuid' => $entity->uuid));
  }

  return t('Student (ID @id)', array('@id' => $entity->student_id));

}

/**
 * Implements hook_theme().
 */
function student_theme() {
  return array(
    'student' => array(
      'render element' => 'elements',
      'template' => 'student',
    ),
  );
}

/**
 * Generate an array for rendering the given student.
 *
 * @param $student
 *   An student object.
 * @param $view_mode
 *   View mode, e.g. 'full', 'teaser'...
 *
 * @return
 *   An array as expected by drupal_render().
 */
function student_view($student, $view_mode = 'full') {

  // Remove previously built content, if it exists.
  $student->content = array();

  $label = entity_label('student', $student);

  if ($view_mode == 'teaser') {
    $student->content['title'] = array(
      '#markup' => filter_xss($label),
      '#weight' => -5,
    );
  }
  else {
    drupal_set_title($label);
  }

  // Build fields content.
  // In case of a multiple view, node_view_multiple() already ran the
  // 'prepare_view' step. An internal flag prevents the operation from running
  // twice.
  field_attach_prepare_view('student', array($student->student_id => $student), $view_mode);
  entity_prepare_view('student', array($student->student_id => $student));
  $student->content += field_attach_view('student', $student, $view_mode);

  $build = $student->content;
  // We don't need duplicate rendering info in student->content.
  unset($student->content);

  $build += array(
    '#theme' => 'student',
    '#student' => $student,
    '#view_mode' => $view_mode,
  );

  // Add contextual links for this student, except when the student is already being
  // displayed on its own page. Modules may alter this behavior (for example,
  // to restrict contextual links to certain view modes) by implementing
  // hook_student_view_alter().
  if (!empty($student->student_id) && $view_mode != 'full') {
    $build['#contextual_links']['student'] = array('student', array($student->student_id));
  }

  // Allow modules to modify the structured student.
  $type = 'student'; // $type is passed by reference to drupal_alter() so it must be a variable.
  drupal_alter(array('student_view', 'entity_view'), $build, $type);

  return $build;

}

/**
 * Process variables for student.tpl.php
 *
 * The $variables array contains the following arguments:
 * - $student
 * - $view_mode
 * - $page
 *
 * @see student.tpl.php
 */
function template_preprocess_student(&$variables) {

  $variables['view_mode'] = $variables['elements']['#view_mode'];

  // Provide a distinct $teaser boolean.
  $variables['teaser'] = $variables['view_mode'] == 'teaser';

  // Provide a distinct $page boolean.
  $variables['page']      = $variables['view_mode'] == 'full';

  $variables['student'] = $variables['elements']['#student'];
  $student = $variables['student'];

  $uri = entity_uri('student', $student);
  $variables['student_url'] = url($uri['path'], $uri['options']);
  $variables['label']     = check_plain(entity_label('student', $student));

  // Fill the $username variable.
  $student_account = empty($student->uid)? FALSE : user_load($student->uid);
  $variables['username'] = empty($student_account)?  FALSE : theme('username', array('account' => $student_account));

  // Fill the $uuid variable.
  $variables['uuid'] = empty($student->uuid)? FALSE : check_plain($student->uuid);

  $variables = array_merge((array) $student, $variables);

  $variables += array('content' => array());
  foreach (element_children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  field_attach_preprocess('student', $student, $variables['content'], $variables);

  $variables['classes_array'][] = drupal_html_class('student-type-' . $student->type);

  $variables['theme_hook_suggestions'][] = 'student__' . $student->type;
  $variables['theme_hook_suggestions'][] = 'student__' . $student->student_id;

}